{
 "title": "Kubernetes Cron  and Batch Job monitoring",
 "description": "Consolidated Dashboard for Monitoring All Batch job pods and Cronjob in Kubernetes",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cron jobs in AKS-CLUSTER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_cronjob_status_active)",
     "legendFormat": "{{total cronjob}}"
    },
    {
     "expr": "sum(kube_cronjob_status_active) by (cronjob)",
     "legendFormat": "{{cronjob}}"
    }
   ]
  },
  {
   "title": "Batch jobs in AKS-CLUSTER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_job_info)", "legendFormat": "{{total job}}" },
    { "expr": "kube_job_info", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Cron jobs in AWS k8s (For now there is no Cron jobs in aws Cluster)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_cronjob_info)", "legendFormat": "{{total cronjob}}" },
    { "expr": "kube_cronjob_info", "legendFormat": "{{cronjob}}" }
   ]
  },
  {
   "title": "Batch jobs in AWS k8s (for now there is no jobs here)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_job_info)", "legendFormat": "{{total job}}" },
    { "expr": "kube_job_info", "legendFormat": "{{job_name}}" }
   ]
  }
 ]
}