{
 "title": "Kubernetes Clusters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "All Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=~\".+\"})",
     "legendFormat": "Masters"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=\"master\"})",
     "legendFormat": "Masters"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=\"node\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Failure Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"} == 1) - count(kube_node_status_condition{condition=\"Ready\",status=\"false\"} == 0 )",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Memory (GB)"
    }
   ]
  },
  {
   "title": "CPU POD Throttling (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"kube-system\"}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total{namespace=\"kube-system\"}[5m])) > 35",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"default\"}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total{namespace=\"default\"}[5m])) > 35",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"infra\"}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total{namespace=\"infra\"}[5m])) > 35",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Nodes Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m) * 100",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Memory Nodes Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "Capacity" }
   ],
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:) * 100",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"default\"})",
     "legendFormat": "deployment-default"
    },
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"infra\"})",
     "legendFormat": "deployment-infra"
    },
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"kube-system\"})",
     "legendFormat": "deployment-kube-system"
    },
    {
     "expr": "sum(kube_daemonset_status_number_ready{namespace=\"default\"})",
     "legendFormat": "daemonset-default"
    },
    {
     "expr": "sum(kube_daemonset_status_number_ready{namespace=\"infra\"})",
     "legendFormat": "daemonset-infra"
    },
    {
     "expr": "sum(kube_daemonset_status_number_ready{namespace=\"kube-system\"})",
     "legendFormat": "daemonset-kube-system"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=\"kube-system\"})",
     "legendFormat": "statefulset-kube-system"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=\"infra\"})",
     "legendFormat": "statefulset-infra"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=\"default\"})",
     "legendFormat": "statefulset-default"
    }
   ]
  },
  {
   "title": "Terminated Count by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"OOMKilled\"} == 1)",
     "legendFormat": "OOMKilled"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"ContainerCannotRun\"} == 1)",
     "legendFormat": "ContainerCannotRun"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"Error\"} == 1)",
     "legendFormat": "Error"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"Completed\"} == 1)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\".+\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"Ready\",status=\"true\"} == 1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"Ready\",status=\"true\"} == 0)",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"DiskPressure\",status=\"true\"} == 1)",
     "legendFormat": "Disk Pressure"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"MemoryPressure\",status=\"true\"} == 1)",
     "legendFormat": "MemoryPressure"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"OutOfDisk\",status=\"true\"} == 1)",
     "legendFormat": "OutOfDisk"
    },
    {
     "expr": "count(kube_node_status_condition{node=~\".+\",condition=\"PIDPressure\",status=\"true\"} == 1)",
     "legendFormat": "PIDPressure"
    }
   ]
  },
  {
   "title": "Default :: Pod Restarts ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\".+\",namespace=\"default\"} > 10",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Infra :: Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\".+\",namespace=\"infra\"} > 5",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "System :: Pod Restarts ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\".+\",namespace=\"kube-system\"} > 5",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}