{
 "title": "NOC Processes Failure",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Terminated Count by Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"OOMKilled\"} == 1)",
     "legendFormat": "OOMKilled"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"ContainerCannotRun\"} == 1)",
     "legendFormat": "ContainerCannotRun"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"Error\"} == 1)",
     "legendFormat": "Error"
    },
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{pod=~\".+\",reason=\"Completed\"} == 1)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Out Of Memory ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} > 0 ) by (container,reason)",
     "legendFormat": "{{container}}___________{{reason}}"
    }
   ]
  },
  {
   "title": "Process Errors ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{reason=\"Error\",namespace=~\"default|infra|nmgjobs\"} > 0 ) by (container,reason)",
     "legendFormat": "{{container}}_________________{{reason}}"
    }
   ]
  },
  {
   "title": "Out Of Memory - Amazon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} > 0 ) by (container,reason)",
     "legendFormat": "{{container}}___________{{reason}}"
    }
   ]
  },
  {
   "title": "Out Of Memory - AZURE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} > 0 ) by (container,reason)",
     "legendFormat": "{{container}}___________{{reason}}"
    }
   ]
  }
 ]
}