{
 "title": "nodes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "content": "<nav>  \n   \n</nav>\n<div id=\"container\">\n  <h1><span>Amazon</span></h1>\n  <div class='split-color'>Cluster</div>\n</div>\n\n",
   "targets": [
    { "legendFormat": "Masters" }
   ]
  },
  {
   "title": "All Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=~\".+\"})",
     "legendFormat": "Masters"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Memory (GB)"
    }
   ]
  },
  {
   "title": "Failure Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"} == 1) - count(kube_node_status_condition{condition=\"Ready\",status=\"false\"} == 0 )",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Cluster Name",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "content": "<nav>  \n   \n</nav>\n<div id=\"container\">\n  <h1><span>Azure</span></h1>\n  <div class='split-color'>Cluster</div>\n</div>\n\n\n",
   "targets": [
    { "legendFormat": "Masters" }
   ]
  },
  {
   "title": "All Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_procs_running)", "legendFormat": "Masters" }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kubernetes_io_role=\"master\"})",
     "legendFormat": "Masters"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Memory (GB)"
    }
   ]
  },
  {
   "title": "Failure Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Nodes"
    }
   ]
  }
 ]
}