{
 "title": "SQS Queues",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue_name",
    "label": "Queue",
    "query": "label_values(aws_sqs_approximate_number_of_messages_visible_average,queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "SQS Prod Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{queue_name=~\"FilesReadyForUpload|ErrorProcessesFiles|ResFilesReadyForUpload|ResErrorProcessesFiles\"}",
     "legendFormat": "{{queue_name}}-[visible]"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average{queue_name=~\"FilesReadyForUpload|ErrorProcessesFiles|ResFilesReadyForUpload|ResErrorProcessesFiles\"}",
     "legendFormat": "{{queue_name}}-[not visible]"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average{queue_name=~\"FilesReadyForUpload|ErrorProcessesFiles|ResFilesReadyForUpload|ResErrorProcessesFiles\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "SQS Visible Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{queue_name=~\"$queue_name\"} > 0",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "SQS Not Visible Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average{queue_name=~\"$queue_name\"} > 0",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "SQS Delayed Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average{queue_name=~\"$queue_name\"} > 0",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}